#!/usr/bin/env bash
# generate-manifest.sh — Template generator for S3 Guardian acceptance test manifests
#
# Usage: generate-manifest.sh PRD-ID "PRD Title" [/path/to/impl-repo]
#
# Creates:
#   acceptance-tests/PRD-ID/manifest.yaml   (template with placeholders)
#   acceptance-tests/PRD-ID/scenarios.feature (empty Gherkin template)
#
# The generated files contain placeholder values that must be filled in
# by the guardian after analyzing the PRD.

set -euo pipefail

# --- Argument Parsing ---

if [ $# -lt 2 ]; then
    echo "Usage: $0 PRD-ID \"PRD Title\" [/path/to/impl-repo]"
    echo ""
    echo "Examples:"
    echo "  $0 PRD-AUTH-001 \"Authentication System\""
    echo "  $0 PRD-PIPELINE-002 \"Prefect Pipeline Integration\" /path/to/project"
    exit 1
fi

PRD_ID="$1"
PRD_TITLE="$2"
IMPL_REPO="${3:-/path/to/implementation/repo}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# --- Resolve acceptance-tests directory ---
# Look for the config repo root by finding .claude/skills/cobuilder-guardian
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# acceptance-tests lives at the config repo root (sibling to .claude/)
TESTS_DIR="${CONFIG_ROOT}/acceptance-tests/${PRD_ID}"

# --- Safety Check ---

if [ -d "$TESTS_DIR" ]; then
    echo "WARNING: Directory already exists: $TESTS_DIR"
    echo "Existing files will NOT be overwritten."
    echo "To regenerate, remove the directory first: rm -rf $TESTS_DIR"
    exit 1
fi

# --- Create Directory ---

mkdir -p "$TESTS_DIR"
echo "Created: $TESTS_DIR/"

# --- Generate manifest.yaml ---

cat > "$TESTS_DIR/manifest.yaml" << MANIFEST_EOF
# Guardian Acceptance Test Manifest
# Generated by: generate-manifest.sh
# Date: ${TIMESTAMP}
#
# INSTRUCTIONS:
#   1. Read the PRD and extract all testable features
#   2. Replace placeholder features below with actual features from the PRD
#   3. Assign weights based on business criticality (MUST sum to 1.00)
#   4. Adjust thresholds if needed for this initiative
#   5. Write Gherkin scenarios in scenarios.feature
#   6. Update scenario references in this manifest

prd_id: "${PRD_ID}"
prd_title: "${PRD_TITLE}"
created_at: "${TIMESTAMP}"
created_by: "cobuilder-guardian"
impl_repo: "${IMPL_REPO}"

# Scoring thresholds — adjust per initiative
thresholds:
  accept: 0.60       # Weighted score >= this → ACCEPT
  investigate: 0.40   # Weighted score >= this but < accept → INVESTIGATE
  reject: 0.40        # Weighted score < this → REJECT

# Validation protocol
validation_protocol:
  evidence_sources:
    - git_diff          # Check actual code changes
    - file_contents     # Read implementation files
    - test_results      # Run test suite if available
    - import_graph      # Verify dependency connections
  require_test_execution: false   # Set true if test suite must be runnable
  time_limit_hours: 3             # Max guardian session duration

# Features with weights — REPLACE THESE WITH ACTUAL PRD FEATURES
# Weights MUST sum to 1.00
features:
  - name: "Feature 1 — Core Functionality"
    description: "REPLACE: Primary feature from PRD"
    weight: 0.30
    scenarios:
      - "feature_1_scenario_a"
      - "feature_1_scenario_b"

  - name: "Feature 2 — Secondary Functionality"
    description: "REPLACE: Second most important feature"
    weight: 0.25
    scenarios:
      - "feature_2_scenario_a"

  - name: "Feature 3 — Supporting Functionality"
    description: "REPLACE: Supporting feature"
    weight: 0.20
    scenarios:
      - "feature_3_scenario_a"

  - name: "Feature 4 — Configuration/Infrastructure"
    description: "REPLACE: Infrastructure or config feature"
    weight: 0.15
    scenarios:
      - "feature_4_scenario_a"

  - name: "Feature 5 — Polish/Observability"
    description: "REPLACE: Observability, docs, or polish feature"
    weight: 0.10
    scenarios:
      - "feature_5_scenario_a"

# Weight verification
total_weight: 1.00
MANIFEST_EOF

echo "Generated: $TESTS_DIR/manifest.yaml"

# --- Generate scenarios.feature ---

cat > "$TESTS_DIR/scenarios.feature" << FEATURE_EOF
# Guardian Acceptance Test Scenarios: ${PRD_ID}
# ${PRD_TITLE}
#
# Generated by: generate-manifest.sh
# Date: ${TIMESTAMP}
#
# INSTRUCTIONS:
#   1. Replace each Feature/Scenario below with actual tests from PRD analysis
#   2. Every scenario MUST include:
#      - Given/When/Then clauses
#      - Confidence Scoring Guide (0.0-1.0 calibration)
#      - Evidence to Check (specific files, functions, tests)
#      - Red Flags (indicators of incomplete or false claims)
#   3. Scenario names must match those listed in manifest.yaml

Feature: Feature 1 — Core Functionality
  Weight: 0.30
  Description: REPLACE with actual PRD feature description

  Scenario: feature_1_scenario_a
    Given REPLACE with precondition
    When REPLACE with action or examination
    Then REPLACE with expected outcome

    # Confidence Scoring Guide:
    # 0.0 — REPLACE: What total absence looks like
    # 0.2 — REPLACE: What a stub/token implementation looks like
    # 0.4 — REPLACE: What a partial/broken implementation looks like
    # 0.6 — REPLACE: What a functional but incomplete implementation looks like
    # 0.8 — REPLACE: What a solid implementation with minor gaps looks like
    # 1.0 — REPLACE: What a complete, production-quality implementation looks like
    #
    # Evidence to Check:
    #   - REPLACE: specific file path or pattern
    #   - REPLACE: specific function or class name
    #   - REPLACE: specific test file or test name
    #
    # Red Flags:
    #   - REPLACE: indicator of false or inflated claims
    #   - REPLACE: common shortcut that looks complete but isn't

  Scenario: feature_1_scenario_b
    Given REPLACE with precondition
    When REPLACE with action or examination
    Then REPLACE with expected outcome

    # Confidence Scoring Guide:
    # 0.0 — REPLACE
    # 0.5 — REPLACE
    # 1.0 — REPLACE
    #
    # Evidence to Check:
    #   - REPLACE
    #
    # Red Flags:
    #   - REPLACE

Feature: Feature 2 — Secondary Functionality
  Weight: 0.25
  Description: REPLACE with actual PRD feature description

  Scenario: feature_2_scenario_a
    Given REPLACE with precondition
    When REPLACE with action or examination
    Then REPLACE with expected outcome

    # Confidence Scoring Guide:
    # 0.0 — REPLACE
    # 0.5 — REPLACE
    # 1.0 — REPLACE
    #
    # Evidence to Check:
    #   - REPLACE
    #
    # Red Flags:
    #   - REPLACE

Feature: Feature 3 — Supporting Functionality
  Weight: 0.20
  Description: REPLACE with actual PRD feature description

  Scenario: feature_3_scenario_a
    Given REPLACE with precondition
    When REPLACE with action or examination
    Then REPLACE with expected outcome

    # Confidence Scoring Guide:
    # 0.0 — REPLACE
    # 0.5 — REPLACE
    # 1.0 — REPLACE
    #
    # Evidence to Check:
    #   - REPLACE
    #
    # Red Flags:
    #   - REPLACE

Feature: Feature 4 — Configuration/Infrastructure
  Weight: 0.15
  Description: REPLACE with actual PRD feature description

  Scenario: feature_4_scenario_a
    Given REPLACE with precondition
    When REPLACE with action or examination
    Then REPLACE with expected outcome

    # Confidence Scoring Guide:
    # 0.0 — REPLACE
    # 0.5 — REPLACE
    # 1.0 — REPLACE
    #
    # Evidence to Check:
    #   - REPLACE
    #
    # Red Flags:
    #   - REPLACE

Feature: Feature 5 — Polish/Observability
  Weight: 0.10
  Description: REPLACE with actual PRD feature description

  Scenario: feature_5_scenario_a
    Given REPLACE with precondition
    When REPLACE with action or examination
    Then REPLACE with expected outcome

    # Confidence Scoring Guide:
    # 0.0 — REPLACE
    # 0.5 — REPLACE
    # 1.0 — REPLACE
    #
    # Evidence to Check:
    #   - REPLACE
    #
    # Red Flags:
    #   - REPLACE
FEATURE_EOF

echo "Generated: $TESTS_DIR/scenarios.feature"

# --- Summary ---

echo ""
echo "=== Acceptance Test Scaffold Created ==="
echo ""
echo "  Directory: $TESTS_DIR/"
echo "  Manifest:  $TESTS_DIR/manifest.yaml"
echo "  Scenarios: $TESTS_DIR/scenarios.feature"
echo ""
echo "Next steps:"
echo "  1. Read the PRD: $IMPL_REPO/docs/prds/${PRD_ID}.md"
echo "  2. Replace placeholder features in manifest.yaml with actual PRD features"
echo "  3. Write Gherkin scenarios in scenarios.feature"
echo "  4. Verify feature weights sum to 1.00"
echo "  5. Begin guardian workflow (Phase 2: Operator Spawning)"
